### PR TITLE
Read cert CA for https agent

### PR DESCRIPTION
**Pull request by elferherrera**
Option to enable reading certificate file for client

### CODE REVIEW

**Review by regadas — CHANGES_REQUESTED** [review]
I think it would be good if we could offer supplying CA cert regardless if we reject unauthorized. wdyt?

**Comment by elferherrera** [comment]
>I think it would be good if we could offer supplying CA cert regardless if we reject unauthorized. wdyt?
to make it compulsory to supply a CA?

**Review by regadas — COMMENTED** [review]
Hi @elferherrera I took a different approach on adding ssl with #203. lmkwyt.

**Comment by elferherrera** [comment]
>Hi @elferherrera I took a different approach on adding ssl with https://github.com/regadas/trino-js-client/pull/203. lmkwyt.

Is using TLS better than modifying the agent?

**Comment by regadas** [comment]
@elferherrera apologies for late reply! we are still passing options (modifying) the agent but we are now leveraging http lib tls options.

**Comment by regadas** [comment]
Closing this. Thank you for starting this! ❤️

**Pull request closed without merging**
